version: 2
jobs:
    build:
        docker:
            - image: circleci/node:16.13

        working_directory: ~/repo

        steps:
            - checkout
            - run: sudo apt install -y rsync

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-

            - run: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            - run: |
                if [ "${CIRCLE_BRANCH}" == "dev" ]
                then
                    cp env.dev.json env.json
                elif [ "${CIRCLE_BRANCH}" == "master" ]
                then
                    cp env.prod.json env.json
                fi

            - run: yarn build

            - deploy:
                command: |
                    if [ "${CIRCLE_BRANCH}" == "dev" ]
                    then
                        rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" -arvc www/* $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH_TEST/www
                    elif [ "${CIRCLE_BRANCH}" == "master" ]
                    then
                        rsync -e "ssh -o StrictHostKeyChecking=no -o  UserKnownHostsFile=/dev/null" -arvc www/* $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH/www
                    fi
